# One project-local backend for ZIP, 7z, TAR and gzip. No global tool installs.
set(ZLIB_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
FetchContent_Declare(ac_zlib GIT_REPOSITORY https://github.com/madler/zlib.git GIT_TAG 51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf # v1.3.1
    SYSTEM)
FetchContent_MakeAvailable(ac_zlib)
set_target_properties(zlib PROPERTIES EXCLUDE_FROM_ALL TRUE)
set(ZLIB_FOUND TRUE)
set(ZLIB_INCLUDE_DIR "${ac_zlib_SOURCE_DIR};${ac_zlib_BINARY_DIR}" CACHE STRING "" FORCE)
set(ZLIB_LIBRARY zlibstatic CACHE STRING "" FORCE)
set(ZLIB_LIBRARIES zlibstatic)
set(XZ_NLS OFF CACHE BOOL "" FORCE)
set(XZ_DOC OFF CACHE BOOL "" FORCE)
set(XZ_TOOLS OFF CACHE BOOL "" FORCE)
set(XZ_TESTS OFF CACHE BOOL "" FORCE)
foreach(tool XZ XZDEC LZMADEC LZMAINFO)
    set(XZ_TOOL_${tool} OFF CACHE BOOL "" FORCE)
endforeach()
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(ac_xz GIT_REPOSITORY https://github.com/tukaani-project/xz.git GIT_TAG a522a226545730551f7e7c2685fab27cf567746c # v5.8.1
    SYSTEM)
set(_ac_testing "${BUILD_TESTING}")
set(BUILD_TESTING OFF)
FetchContent_MakeAvailable(ac_xz)
set(BUILD_TESTING "${_ac_testing}")
set(LIBLZMA_INCLUDE_DIR "${ac_xz_SOURCE_DIR}/src/liblzma/api" CACHE PATH "" FORCE)
set(LIBLZMA_LIBRARY liblzma CACHE STRING "" FORCE)
set(LIBLZMA_HAS_AUTO_DECODER TRUE CACHE BOOL "" FORCE)
set(LIBLZMA_HAS_EASY_ENCODER TRUE CACHE BOOL "" FORCE)
set(LIBLZMA_HAS_LZMA_PRESET TRUE CACHE BOOL "" FORCE)
foreach(feature BZip2 LZ4 ZSTD OPENSSL NETTLE LIBB2 LIBXML2 EXPAT ICONV PCREPOSIX PCRE2POSIX CNG)
    set(ENABLE_${feature} OFF CACHE BOOL "" FORCE)
endforeach()
set(ENABLE_ZLIB ON CACHE BOOL "" FORCE)
set(ENABLE_LZMA ON CACHE BOOL "" FORCE)
set(ENABLE_TEST OFF CACHE BOOL "" FORCE)
set(ENABLE_INSTALL OFF CACHE BOOL "" FORCE)
set(ENABLE_TAR OFF CACHE BOOL "" FORCE)
set(ENABLE_CPIO OFF CACHE BOOL "" FORCE)
set(ENABLE_CAT OFF CACHE BOOL "" FORCE)
set(ENABLE_UNZIP OFF CACHE BOOL "" FORCE)
set(ENABLE_ACL OFF CACHE BOOL "" FORCE)
set(ENABLE_XATTR OFF CACHE BOOL "" FORCE)
FetchContent_Declare(ac_archive GIT_REPOSITORY https://github.com/libarchive/libarchive.git GIT_TAG 27cbc7827172698143e440801fc0ba39ccb4f1f5 # v3.8.9
    SYSTEM)
FetchContent_MakeAvailable(ac_archive)
target_include_directories(archive_static SYSTEM PUBLIC "${ac_archive_SOURCE_DIR}/libarchive" "${ac_archive_BINARY_DIR}")
target_compile_definitions(archive_static PUBLIC LIBARCHIVE_STATIC)
target_link_libraries(archive_static zlibstatic liblzma)
if(WIN32)
    target_link_libraries(archive_static bcrypt)
endif()
configure_file("${ac_archive_SOURCE_DIR}/COPYING" "${AC_DEPENDENCY_LICENSE_DIR}/libarchive-COPYING.txt" COPYONLY)
configure_file("${ac_zlib_SOURCE_DIR}/LICENSE" "${AC_DEPENDENCY_LICENSE_DIR}/zlib-LICENSE.txt" COPYONLY)
configure_file("${ac_xz_SOURCE_DIR}/COPYING" "${AC_DEPENDENCY_LICENSE_DIR}/xz-COPYING.txt" COPYONLY)
